FROM amazonlinux
MAINTAINER sam <sami.vtf@gmail.com>
RUN yum install python3 python3-pip -y
RUN pip3 install Flask
COPY app.py /opt/app.py
ENTRYPOINT FLASK_APP=/opt/app.py flask run --host=0.0.0.0 --port=8080
EXPOSE 8080
